### ISSUE TITLE
Identical rows with nested arrays will have the same ID linking to child

### ISSUE THREAD

**Issue by kachnitel** [keboola/php-jsonparser#3]
When multiple identical JSON objects in an array have the exact same contents, which includes an array, the "parent-child" link created using a hash of the column will be the same for both rows, resulting in multiplicated associations between the CSV files. 

Example:

```
[
  {
    "a":"b",
    "arr": [1,2]
  },
  {
    "a":"b",
    "arr": [1,2]
  }
]
```

would result in both rows being linked to values from each other.

**Comment by kachnitel** [comment]
282cdfc Fixes the problem for nested arrays within identical objects WITHIN another non-identical object, but not if the object is identical within the root.

**Comment by odinuv** [comment]
shouldn't really be a problem in root, unless someone runs into it, this is wont'fix
